server:
  port: 9001
spring:
  application:
    name: Student-Management-Service
  profiles:
    active:
      - dev
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


resilience4j:
  circuitbreaker:
    instances:
      feeReceiptServiceCB:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 5s
